name: picsum
description: A new Flutter project.

version: 1.4.0+16

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dynamic_color: ^1.6.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.2
  # gallery_saver:
  #   git:
  #     url: https://github.com/anoochit/gallery_saver.git
  get: ^4.6.5
  http: ^1.2.1
  # image_gallery_saver: ^2.0.3
  image_gallery_saver_plus: ^4.0.1
  lazy_load_scrollview: ^1.3.0
  path_provider: ^2.0.12

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  package_rename: ^1.0.0+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/launcher_icon.png"

package_rename_config:
  android:
    app_name: "picsum"
    package_name: "net.redlinesoft.picsum"

  ios:
    app_name: "picsum"
    bundle_name: "net.redlinesoft.picsum"
    package_name: "net.redlinesoft.picsum"

flutter:
  uses-material-design: true
