name: picsum
description: A new Flutter project.

version: 1.3.4+7

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dynamic_color: ^1.6.2
  flutter:
    sdk: flutter
  gallery_saver: ^2.3.2
  get: ^4.6.5
  http: ^0.13.5
  lazy_load_scrollview: ^1.3.0
  path_provider: ^2.0.12

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  package_rename: ^1.0.0+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/launcher_icon.png"

package_rename_config:
  android:
    app_name: "picsum"
    package_name: "net.redlinesoft.picsum"

  ios:
    app_name: "picsum"
    bundle_name: "net.redlinesoft.picsum"
    package_name: "net.redlinesoft.picsum"

flutter:
  uses-material-design: true
