name: "Build & Release"

on:
  push:
    branches: [master]

env:
  PROPERTIES_PATH: "./android/key.properties"

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Generate key.properties file for Android signing
      - name: Generate key.properties
        run: |
          echo keyPassword=${{ secrets.KEY_STORE }} > ${{ env.PROPERTIES_PATH }}
          echo storePassword=${{ secrets.KEY_PASSWORD }} >> ${{ env.PROPERTIES_PATH }}
          echo keyAlias=${{ secrets.KEY_ALIAS }} >> ${{ env.PROPERTIES_PATH }}

      # Decode keystore file from base64
      - name: Decode Keystore File
        run: echo "${{ secrets.KEYSTORE2 }}" | base64 --decode > android/app/key.jks

      # Get dependencies
      - name: Get Flutter dependencies
        run: flutter pub get

      # Build AAB
      - name: Build Android App Bundle
        run: flutter build appbundle

      # Build APKs for all ABIs
      - name: Build APK (split-per-ABI)
        run: flutter build apk --split-per-abi

      # Optional: Build iOS without code signing
      # - name: Build iOS App (No Codesign)
      #   run: |
      #     flutter build ios --no-codesign
      #     cd build/ios/iphoneos
      #     mkdir Payload
      #     cd Payload
      #     ln -s ../Runner.app
      #     cd ..
      #     zip -r app.ipa Payload

      # Extract version and set tag
      - name: Extract version from pubspec.yaml
        run: echo "APP_VERSION=$(grep 'version: ' pubspec.yaml | sed 's/version: //')" >> $GITHUB_ENV

      # Release artifacts
      - name: Push to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/bundle/release/*.aab,
            build/app/outputs/flutter-apk/*.apk
          tag: v${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
